// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-RqdzhpAXj7mhnL_v82ghKuSSAZ2OEm0',
    appId: '1:1020113093828:web:be8a86e5fff37e149b3591',
    messagingSenderId: '1020113093828',
    projectId: 'auck-3909a',
    authDomain: 'auck-3909a.firebaseapp.com',
    storageBucket: 'auck-3909a.appspot.com',
    measurementId: 'G-S4JWE75NQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyLzNW5kpKlbb97gtNcanGGWSTAqHLBk',
    appId: '1:1020113093828:android:eebb5bfc58dccb259b3591',
    messagingSenderId: '1020113093828',
    projectId: 'auck-3909a',
    storageBucket: 'auck-3909a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFZBZ5GCyRpVejdagU8dvwwUFNp1xtYg',
    appId: '1:1020113093828:ios:6414517b01e31d379b3591',
    messagingSenderId: '1020113093828',
    projectId: 'auck-3909a',
    storageBucket: 'auck-3909a.appspot.com',
    iosClientId: '1020113093828-8htblqmempak0725i976a1pifsda8vu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.agave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFZBZ5GCyRpVejdagU8dvwwUFNp1xtYg',
    appId: '1:1020113093828:ios:44d340660c62c1539b3591',
    messagingSenderId: '1020113093828',
    projectId: 'auck-3909a',
    storageBucket: 'auck-3909a.appspot.com',
    iosClientId: '1020113093828-7h1r7qu99k8gqeue6bp4lh73gjrvfd5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.agave.RunnerTests',
  );
}
